spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yesset.assan@gmail.com
    password: tnvqyiriqnefkzwt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  liquibase:
    change-log: db/main-data.xml
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5450/user
redis:
  host: localhost
  port: 6379


springdoc:
  swagger-ui:
    path: /user-documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    enabled: true
    path: /user-docs
  openapi:
    info:
      title: Custom API Documentation Title # Custom title for your API docs
      description: This is the custom description of your API.
      version: 1.0.0
server:
  port: 8099

