spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yesset.assan@gmail.com
    password: tnvqyiriqnefkzwt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  liquibase:
    change-log: db/main-data.xml
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Qasaqayj7
    url: jdbc:postgresql://localhost:5432/customer
jwt:
  secret: 56e4rg64re654g65fg4rev6
  lifetime: 1m

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
