spring:
  config:
    import: optional:configserver:http://localhost:88888
  application:
    name: product-service
  liquibase:
    change-log: db/main-data.xml
    enabled: true
    drop-first: true
    default-schema:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/product
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8050

redis:
  host: localhost
  port: 6379

