version: "3.0"
services:
  user_db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5450:5432
    container_name: user_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
  order_db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5451:5432
    container_name: order_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order
  product_db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5452:5432
    container_name: product_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
  notification_db:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: notification
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9093:9092"
  zipkin:
    image: openzipkin/zipkin:2.23.16
    container_name: zipkin
    ports:
      - "9411:9411"

volumes:
  mongo_data: