spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888/
  mail:
    host: smtp.gmail.com
    port: 587
    username: yesset.assan@gmail.com
    password: tnvqyiriqnefkzwt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  liquibase:
    change-log: db/main-data.xml
    enabled: true
    drop-first: true
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5450/user
redis:
  host: localhost
  port: 6379
springdoc:
  swagger-ui:
    disable-swagger-default-url: true

jwt:
  secret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566D
  lifetime: 30m

server:
  port: 8099
