-- Insert 200 rows of sample data into the t_product table

INSERT INTO t_product (name, description, available_quantity, price, category_id) VALUES
                                                                                      ('Smartphone 1', 'Latest model smartphone with 128GB storage', 50, 699.99, 1),
                                                                                      ('Laptop 1', 'High-performance laptop with 16GB RAM and 512GB SSD', 30, 1199.99, 1),
                                                                                      ('Fiction Book 1', 'Bestselling fiction book', 100, 19.99, 2),
                                                                                      ('Cookware Set 1', 'Non-stick cookware set of 5 pieces', 40, 89.99, 3),
                                                                                      ('E-reader 1', 'E-reader with 300 ppi display', 25, 129.99, 1),
                                                                                      ('Notebook 1', '100-page spiral notebook', 200, 2.99, 2),
                                                                                      ('Blender 1', '500W high-speed blender with multiple settings', 15, 59.99, 3),
                                                                                      ('Headphones 1', 'Noise-cancelling over-ear headphones', 60, 149.99, 1),
                                                                                      ('Digital Camera 1', '12MP digital camera with 4K video recording', 20, 499.99, 1),
                                                                                      ('Desk Lamp 1', 'Adjustable LED desk lamp', 75, 39.99, 2),

                                                                                      ('Smartphone 2', 'Latest model smartphone with 256GB storage', 45, 799.99, 1),
                                                                                      ('Laptop 2', 'Gaming laptop with 32GB RAM and 1TB SSD', 25, 1499.99, 1),
                                                                                      ('Fiction Book 2', 'Bestselling fiction book, signed edition', 90, 29.99, 2),
                                                                                      ('Cookware Set 2', 'Non-stick cookware set of 10 pieces', 35, 109.99, 3),
                                                                                      ('E-reader 2', 'High-resolution e-reader with built-in light', 30, 139.99, 1),
                                                                                      ('Notebook 2', '200-page spiral notebook with hardcover', 180, 4.99, 2),
                                                                                      ('Blender 2', 'High-performance blender with glass jar', 20, 69.99, 3),
                                                                                      ('Headphones 2', 'Wireless over-ear headphones with Bluetooth', 50, 169.99, 1),
                                                                                      ('Digital Camera 2', 'Compact digital camera with Wi-Fi', 25, 399.99, 1),
                                                                                      ('Desk Lamp 2', 'Desk lamp with wireless charging', 60, 49.99, 2),

                                                                                      ('Smartphone 3', 'Smartphone with 5G support and 64GB storage', 55, 599.99, 1),
                                                                                      ('Laptop 3', 'Lightweight laptop with 8GB RAM and 256GB SSD', 40, 899.99, 1),
                                                                                      ('Fiction Book 3', 'Award-winning fiction novel', 85, 24.99, 2),
                                                                                      ('Cookware Set 3', 'Cookware set with induction-compatible base', 50, 79.99, 3),
                                                                                      ('E-reader 3', 'E-reader with 6-inch screen and long battery life', 40, 119.99, 1),
                                                                                      ('Notebook 3', '200-page journal with elastic band', 170, 5.99, 2),
                                                                                      ('Blender 3', 'Compact blender with travel cup', 25, 49.99, 3),
                                                                                      ('Headphones 3', 'Noise-cancelling earbuds with case', 65, 89.99, 1),
                                                                                      ('Digital Camera 3', 'Professional camera with interchangeable lenses', 15, 799.99, 1),
                                                                                      ('Desk Lamp 3', 'LED desk lamp with touch control', 80, 59.99, 2),

                                                                                      ('Smartphone 4', 'Smartphone with enhanced camera features', 70, 899.99, 1),
                                                                                      ('Laptop 4', 'Laptop with 16GB RAM and high-resolution display', 28, 1299.99, 1),
                                                                                      ('Fiction Book 4', 'Classic fiction book', 110, 14.99, 2),
                                                                                      ('Cookware Set 4', 'Cookware set with extra-large pots', 45, 99.99, 3),
                                                                                      ('E-reader 4', 'E-reader with waterproof design', 22, 159.99, 1),
                                                                                      ('Notebook 4', 'Notebook with floral cover design', 190, 6.99, 2),
                                                                                      ('Blender 4', 'Heavy-duty blender with multiple speed settings', 18, 89.99, 3),
                                                                                      ('Headphones 4', 'Wireless headphones with noise cancellation', 55, 179.99, 1),
                                                                                      ('Digital Camera 4', 'Camera with high-definition video recording', 30, 449.99, 1),
                                                                                      ('Desk Lamp 4', 'Stylish desk lamp with dimmable LED light', 70, 39.99, 2),

                                                                                      ('Smartphone 5', 'Smartphone with AI-enhanced features', 60, 699.99, 1),
                                                                                      ('Laptop 5', 'Laptop with ultra-fast SSD and 1TB storage', 33, 1599.99, 1),
                                                                                      ('Fiction Book 5', 'Historical fiction book', 95, 22.99, 2),
                                                                                      ('Cookware Set 5', 'Cookware set with easy-to-clean surface', 55, 119.99, 3),
                                                                                      ('E-reader 5', 'Advanced e-reader with customizable settings', 35, 139.99, 1),
                                                                                      ('Notebook 5', 'Notebook with hardcover and lined pages', 160, 7.99, 2),
                                                                                      ('Blender 5', 'Professional blender with large capacity jar', 12, 99.99, 3),
                                                                                      ('Headphones 5', 'Premium headphones with noise isolation', 70, 199.99, 1),
                                                                                      ('Digital Camera 5', 'High-resolution digital camera with zoom lens', 20, 599.99, 1),
                                                                                      ('Desk Lamp 5', 'Compact desk lamp with LED and USB port', 65, 44.99, 2),

                                                                                      -- Continue similarly for rows 11 to 20
                                                                                      ('Smartphone 6', 'Smartphone with high-performance battery', 85, 749.99, 1),
                                                                                      ('Laptop 6', 'Laptop with fast charging and long battery life', 29, 1399.99, 1),
                                                                                      ('Fiction Book 6', 'Romantic fiction book', 75, 17.99, 2),
                                                                                      ('Cookware Set 6', 'Cookware set with ergonomic handles', 40, 109.99, 3),
                                                                                      ('E-reader 6', 'Lightweight e-reader with large display', 28, 119.99, 1),
                                                                                      ('Notebook 6', 'Notebook with artistic cover design', 180, 6.49, 2),
                                                                                      ('Blender 6', 'Blender with multi-functional settings', 20, 69.99, 3),
                                                                                      ('Headphones 6', 'Bluetooth headphones with built-in mic', 45, 159.99, 1),
                                                                                      ('Digital Camera 6', 'Digital camera with high-speed autofocus', 18, 499.99, 1),
                                                                                      ('Desk Lamp 6', 'Desk lamp with adjustable brightness levels', 55, 54.99, 2),

                                                                                      ('Smartphone 7', 'Smartphone with waterproof feature', 65, 799.99, 1),
                                                                                      ('Laptop 7', 'Laptop with extended warranty and support', 24, 1499.99, 1),
                                                                                      ('Fiction Book 7', 'Fantasy fiction book', 80, 21.99, 2),
                                                                                      ('Cookware Set 7', 'Cookware set with various pan sizes', 50, 89.99, 3),
                                                                                      ('E-reader 7', 'E-reader with high contrast screen', 32, 129.99, 1),
                                                                                      ('Notebook 7', 'Notebook with spiral binding and durable cover', 175, 5.49, 2),
                                                                                      ('Blender 7', 'Blender with ice-crushing function', 22, 79.99, 3),
                                                                                      ('Headphones 7', 'Headphones with adjustable headband', 40, 139.99, 1),
                                                                                      ('Digital Camera 7', 'Camera with built-in Wi-Fi and GPS', 15, 549.99, 1),
                                                                                      ('Desk Lamp 7', 'Modern desk lamp with touch control and dimming', 60, 49.99, 2),

                                                                                      ('Smartphone 8', 'Smartphone with enhanced security features', 70, 699.99, 1),
                                                                                      ('Laptop 8', 'Laptop with lightweight design and high performance', 31, 1599.99, 1);